### ISSUE TITLE
Passcode safety

### ISSUE THREAD

**Issue by pardnoj** [project-imas/encrypted-core-data#142]
I am not very familiar with security issues but is it safe to hardcode passcode to database?

**Comment by JirkaKrivanek** [comment]
Sorry for reopening this topic (I may create another one later).

I look into the SQLCipher and is appears to me that SQLCipher actually uses the KEY (any arbitrary byte array) not the PASSWORD (typically limited to display-able characters).

In my company, we have to be knit picking on the security (it is actually a bit annoying) and I will definitely get a hint from my security department when they will be doing the security code review: "Why you are not using the high entropy secure random key, but the ASCII password?" (it already happened to me multiple times - well with Android, I am a kind of new to iOS).

I failed to find this security issue to be clearly described here https://github.com/project-imas/encrypted-core-data (sorry if I missed it).

Could you please elaborate on it? 

So that at least I have some argument when dealing with our security department?
