### ISSUE TITLE
missing sqllite3.c

### ISSUE THREAD

**Issue by venky-seenivasan** [project-imas/encrypted-core-data#150]
Hello, I checked out the SQLCipher submodule and tried to build the project. But I don't see sqllite3.c in this project and the compilation is not going through. Can someone clarify the steps to build this?

Thanks
--Venky

**Comment by venky-seenivasan** [comment]
Quick update on this. Installation via CocoaPod is configuring the project correctly.

Thanks
--Venky

**Comment by zerpt** [comment]
@venky-seenivasan 
I had a similar issue while configuring Travis-CI. I found the `./configure` call by the Run Script Build Step in the SQLCipher project was failing due to a library architecture conflict (particularly on x86_64 arch, probably stemming from attempting to compile with an older SDK). I ended up manually adding the compiler flag `-miphoneos-min-version=6.0` to this Run Script and it fixed the issue.

This may or may not be your solution, but it's worth a shot, and at least documenting it here.
