### ISSUE TITLE
Core data corrupted after app crash

### ISSUE THREAD

**Issue by venky-seenivasan** [project-imas/encrypted-core-data#151]
Hello,
Encrypted core data works great after integration. However it corrupts the core data once the app is crashed. After the app crash, read/write operation fails with below error.

Jan 18 13:46:04 Test TestDemo[4504] <Critical>: Name: NSObjectInaccessibleException
Jan 18 13:46:04 Test TestDemo[4504] <Critical>: Reason: CoreData could not fulfill a fault for '0x174026f00 <x-coredata://96535FDB-865C-42B7-A1EE-ED80C705EC1D/TestSessionsCollection/p1>'

Do I need to do any encrypt core data specific cleanup upon app crash?

Thanks
--Venky

**Comment by venky-seenivasan** [comment]
As per below link, it looks like the object's underlying data has been deleted from the persistent store.
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CoreData/Articles/cdTroubleshooting.html

As a recovery, reinitializing with new object is working fine. 

I could reproduce this error in 2 use cases
1) Crash the app manually from code and launch the app from simulator
2) Run the app from simulator, stop the app from xcode and relaunch the app manually from simulator

But as long the app is not crashed or stopped manually, everything is working fine. So for some reason, the data get lost when the app is crashed/stopped.

Can someone let me know how to diagnose this issue?

Thanks

**Comment by zerpt** [comment]
@venky-seenivasan 
Is there a specific section of code causing this exception? If so, could you post it so I may take a look? This error is basically just CoreData's managed object context being out of sync with the persistent store, particularly having a reference to an object that doesn't actually exist in the store. I don't have any general trouble shooting at the moment, but any offending code might help shed some light.

**Comment by venky-seenivasan** [comment]
@zerpt Thanks for the feedback. Still looking into this issue and found that the issue is related to core data persistence. 

Some background about my application. My application uses background thread to read and write the data to coredata. Core data model uses one to many relationships to store the data. This works fine without the encrypted core data. 

With encrypted core data, save operation is failing with below error.
Error Domain=NSCocoaErrorDomain Code=133020 "The operation couldn’t be completed. (Cocoa error 133020.)" UserInfo=0x7f98c2c16260 {conflictList=(
    "NSMergeConflict (0x7f98c2c3b810) for NSManagedObject (0x7f98c2f39c60) with objectID '0x7f98c2c07230 <x-coredata://091E1870-D295-4DCA-911E-EB4838E09569/TCollection/p1>' with oldVersion = 1 and newVersion = <deleted> and old object snapshot = {\n}"
)}

As the error indicates, there seems to be some merge conflict. But this happens only when i use encrypted core data. Any thoughts?

Thanks

**Comment by zerpt** [comment]
@venky-seenivasan Hmm, this *looks* like a model version issue. That `NSMergeConflict` can happen after making changes to the model, so the persistent store on the device (or simulator) doesn't match what the code is attempting to do. Unfortunately the current version of ECD is lacking a variety of migration support, this being one of them.

If this is your issue, a manual wipe of the app space usually solves it, since the app will then create the persistent store from scratch, thereby matching the newest model.

**Comment by venky-seenivasan** [comment]
@zerpt, Wiping and recreating the persistent store is working. But unfortunately for our use case, we need to retain the old data.

I will try to explore how to extend ECD to support our mode migration. Please let me know if you have some pointers.

**Comment by venky-seenivasan** [comment]
Finally we found the issue. Our current data model looks like below

Root node (Collection)
     -> Child node

The root node don't have any attributes and it just has collection(NSSet) relation to Child node. This works fine in plain mode. But fails in encryption mode. So it looks like ECD need to be enhanced to support this. As a workaround, we just added a temporary attribute to root node and it works fine.

**Comment by issue2k** [comment]
Got a similar problem after including encrypted-coredata to our project (working fine without encryption).

Fetch entity: MvnModel
2015-02-13 19:08:29:543 Drive & Learn[1178:8507] Exporting models: 1
2015-02-13 19:08:29.551 Drive & Learn[1178:546050] *** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'CoreData could not fulfill a fault for '0x17d43910 <x-coredata://C4852F2F-3B68-4B4F-AE35-C675CA564BA9/MvnModel/p1>''
*** First throw call stack:
(0x26c745f7 0x344e6c77 0x2698c435 0x2698b82f 0x2698b697 0x6b82b 0x6a68b 0x79a93 0x8089cb 0x8127bb 0x813881 0x34bc4e25 0x34bc4b78)
libc++abi.dylib: terminating with uncaught exception of type _NSCoreDataException

Basically what is fetching an instance and try to access its properties. As soon as i try to access the first property, this fails:

```
NSArray *modelList = [sharedCoreDataManager fetchEntitiesForClass:@"MvnModel" withPredicate:[NSPredicate predicateWithFormat:@"trip==%@", trip] andSortDescriptors:nil];
for(MvnModel *model in modelList) {
     double meanF1 = [modelInstance.meanF1 doubleValue];
 }
```

as soon as i access the meanF1 propery the app crashes.

The fetch method:

```
- (NSArray *)fetchEntitiesForClass:(NSString *)entityName withPredicate:(NSPredicate *)predicate andSortDescriptors:(NSArray *)sortDescriptors {
    DDLogVerbose(@"Fetch entity: %@", entityName);

    __block NSEntityDescription *entityDescription;
    
    [_mainManagedObjectContext performBlockAndWait:^{
        entityDescription = [NSEntityDescription entityForName:entityName inManagedObjectContext:_mainManagedObjectContext];
    }];

    NSFetchRequest *fetchRequest = [[NSFetchRequest alloc] init];
    fetchRequest.entity = entityDescription;
    fetchRequest.predicate = predicate;
    fetchRequest.sortDescriptors = sortDescriptors;

    __block NSArray *results;
    [_mainManagedObjectContext performBlockAndWait:^{
        NSError *error = nil;
        results = [_mainManagedObjectContext executeFetchRequest:fetchRequest error:&error];
        if(error) {
            DDLogError(@"Error: %@", error.localizedDescription);
        }
    }];

    return results;
}
```

**Comment by issue2k** [comment]
Got a similar problem after including encrypted-coredata to our project (working fine without encryption).

Fetch entity: MvnModel
2015-02-13 19:08:29:543 D&L[1178:8507] Exporting models: 1
2015-02-13 19:08:29.551 D&L[1178:546050] *** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'CoreData could not fulfill a fault for '0x17d43910 <x-coredata://C4852F2F-3B68-4B4F-AE35-C675CA564BA9/MvnModel/p1>''
*** First throw call stack:
(0x26c745f7 0x344e6c77 0x2698c435 0x2698b82f 0x2698b697 0x6b82b 0x6a68b 0x79a93 0x8089cb 0x8127bb 0x813881 0x34bc4e25 0x34bc4b78)
libc++abi.dylib: terminating with uncaught exception of type _NSCoreDataException

Basically what is fetching an instance and try to access its properties. As soon as i try to access the first property, this fails:

```
NSArray *modelList = [sharedCoreDataManager fetchEntitiesForClass:@"MvnModel" withPredicate:[NSPredicate predicateWithFormat:@"trip==%@", trip] andSortDescriptors:nil];
for(MvnModel *model in modelList) {
     double meanF1 = [modelInstance.meanF1 doubleValue];
 }
```

as soon as i access the meanF1 propery the app crashes.

The fetch method:

```
- (NSArray *)fetchEntitiesForClass:(NSString *)entityName withPredicate:(NSPredicate *)predicate andSortDescriptors:(NSArray *)sortDescriptors {
    DDLogVerbose(@"Fetch entity: %@", entityName);

    __block NSEntityDescription *entityDescription;
    
    [_mainManagedObjectContext performBlockAndWait:^{
        entityDescription = [NSEntityDescription entityForName:entityName inManagedObjectContext:_mainManagedObjectContext];
    }];

    NSFetchRequest *fetchRequest = [[NSFetchRequest alloc] init];
    fetchRequest.entity = entityDescription;
    fetchRequest.predicate = predicate;
    fetchRequest.sortDescriptors = sortDescriptors;

    __block NSArray *results;
    [_mainManagedObjectContext performBlockAndWait:^{
        NSError *error = nil;
        results = [_mainManagedObjectContext executeFetchRequest:fetchRequest error:&error];
        if(error) {
            DDLogError(@"Error: %@", error.localizedDescription);
        }
    }];

    return results;
}
```

**Comment by john-langley** [comment]
+1

ECD doesn't appear to support models with abstract parent entities.  I spent a full day trying to understand why I had merge conflicts on save, even after deleting my versioned model and replacing it with an unversioned replacement.

My managed objects were being deleted from the persistent store when the save failed, causing "Core Data cannot fulfill fault" exceptions.

**Comment by dorada** [comment]
Parent entities should now be supported
