### ISSUE TITLE
Include of non-modular header sqlite3 inside framework

### ISSUE THREAD

**Issue by lolgear** [project-imas/encrypted-core-data#192]
I encountered with this issue when I try build Pods framework instead of static library ( swift integration, actually )

MyProject/Pods/EncryptedCoreData/Incremental Store/EncryptedStore.h:8:9: Include of non-modular header inside framework module 'EncryptedCoreData.EncryptedStore'

**Comment by gavin-black** [comment]
@lolgear 

Interesting, I've not ran into this, but likely because we're not using Swift.  Does it cause the library to not work?  Or is it just a warning?

-- Gavin

**Comment by jzzocc** [comment]
@gavin-black The library can't be used at all with the `use_frameworks!` on in CocoaPods (which must be on if you have and pods written in Swift). See http://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module

This can be fixed by removing the `#import <sqlite3.h>` and the signatures of methods that take pointers to `sqlite3_stmt`s in `EncryptedStore.h` since they're only used within `EncryptedStore`. Not sure if any users of this project are using them though.

**Comment by lolgear** [comment]
Any update?

**Comment by gavin-black** [comment]
This looks like an easy fix if it follows the AFNetworking issue.  If someone puts in a pull request that passes in Travis I can take it in.

**Comment by lolgear** [comment]
#202

**Comment by lolgear** [comment]
@gavin-black could you also change release version?
