### ISSUE TITLE
Question about encrypted core data with multiple contexts

### ISSUE THREAD

**Issue by jcavar** [project-imas/encrypted-core-data#199]
Hi,
We are using encrypted core data with multiple contexts. When we integrated this tool https://github.com/GrahamDennis/GDCoreDataConcurrencyDebugging we are seeing a lot of concurrent accesses inside `EncryptedStore.m`. These exceptions occur when we try to save private context which has `NSPrivateQueueConcurrencyType`. Is there some extra step we should do to ensure that `EncryptedStore` does it's job on right thread?

**Comment by mmkrishna2008** [comment]
Hi Jcavar,

We are also getting exception while trying to save private context(NSPrivateQueueConcurrencyType) after including this library in our app. It seems this issue is not happening frequently.
If possible, try to share the steps to reproduce the issue
What kind of exceptions you are getting? 
Are you able to find solution for the issue?

**Comment by jcavar** [comment]
Hi there, 
We are getting exception every time we try to save private context. We use stack where private context is parent of main context. It is concurrent access exception(objects are accessed on queue on which they shouldn't be). We were not able to find a solution yet.

**Comment by mmkrishna2008** [comment]
Hi,

As per Apple documentation, using performBlockAndWait: and performBlock: will make sure all operations on NSManagedObjectContext will be executed on the right thread.

You can debug concurrency issues by adding below launch argument (iOS 8 and above) to your scheme

-com.apple.CoreData.ConcurrencyDebug 1
